# Generated by Django 6.0.6 on 2026-06-28 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(max_length=200, verbose_name='Ten')),
                ('gender', models.CharField(choices=[(1, 'Male'), (0, 'Female')], default=1, verbose_name='Gioi tinh')),
                ('active', models.BooleanField(default=False, verbose_name='Kich hoat')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Thoi gian tao')),
                ('lastAccess', models.DateTimeField(auto_now=True, verbose_name='Lan cuoi truy cap')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Tieu de')),
                ('content', models.TextField(verbose_name='Noi dung')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Ngay dang')),
                ('updateAt', models.DateTimeField(auto_now_add=True, verbose_name='Ngay cap nhat')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.client', verbose_name='Tac gia')),
            ],
        ),
    ]
