# Generated by Django 4.0.10 on 2026-01-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
